//
// PPx Version (ppxver.plÇ…ÇÊÇÈé©ìÆê∂ê¨)
//
#ifndef WS_CAPTION // for resource include
#include <windows.h>
#include <winuser.h>
#endif

#define VersionH		2
#define VersionM		0
#define VersionL		8
#define VersionP		0
#define FileProp_Version	"2.08"		// for Propaty sheet
#define FileCfg_Version	"2.08"	// for CFGver
#define X_Version		"2.0.8.0"	// for XML
#define Q_Version		2,0,8,0	// for Quick view
#define COM_ver			Q_Version	// Common
#define BUI_ver			Q_Version	// bUI
#define CUI_ver			Q_Version	// cUI
#define VUI_ver			Q_Version	// vUI
#define ReleaseYear		"2026"
